#!/usr/bin/env python3
"""Generate docs/MITRE_COVERAGE.md and the "what we can detect" Navigator layer from rules.yaml.

Run after editing rules:  python scripts/gen_mitre_coverage.py
"""

from __future__ import annotations

import json
from pathlib import Path

from honeylens.mitre.attack import coverage, default_rules, load_snapshot, navigator_layer

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    rules = default_rules()
    cov = coverage(rules)
    snap = load_snapshot()
    lines = [
        "# MITRE ATT&CK coverage",
        "",
        "> Generated by `scripts/gen_mitre_coverage.py` from `src/honeylens/mitre/rules.yaml`. Do not edit by hand.",
        "",
        "**What:** which ATT&CK (Adversarial Tactics, Techniques, and Common Knowledge) techniques HoneyLens can",
        "recognise in attacker commands. **Why:** mapping raw commands to a shared vocabulary lets you compare",
        "your honeypot with threat reports and explain findings in a SOC (Security Operations Centre).",
        "",
        f"* ATT&CK version: **Enterprise v{cov['attack_version']}** (official STIX, SHA-256 `{snap['source_sha256']}`)",
        f"* Rules: **{cov['rules']}** across **{len(cov['tactics_covered'])} tactics**",
        f"* Distinct techniques covered: **{len(cov['techniques_covered'])}**",
        f"* Coverage: **{cov['coverage_percent']}%** of the {cov['active_techniques_in_covered_tactics']} active (not revoked/deprecated)",
        "  techniques in the tactics we cover. Most of the rest are Windows/cloud/network techniques an SSH",
        "  honeypot can never see, so this number is a planning aid, not a grade.",
        "",
        "**v19 note:** ATT&CK v19 split *Defense Evasion* into **Stealth** (TA0005) and **Defense Impairment**",
        "(TA0112). The classic \"defense evasion\" category is covered by both. *Resource hijacking* is",
        "T1496.001 Compute Hijacking under **Impact**.",
        "",
        "## Rules per tactic",
        "",
        "| Tactic | ID | Rules |",
        "|---|---|---|",
    ]
    for tactic, n in cov["rules_per_tactic"].items():
        lines.append(f"| {tactic} | {snap['tactics'].get(tactic, {}).get('id', '')} | {n} |")
    lines += ["", "## All rules", "", "| Rule | Technique | Tactic | Confidence | Rationale |", "|---|---|---|---|---|"]
    for r in rules:
        lines.append(f"| {r.id} | {r.technique} {r.technique_name} | {r.tactic} | {r.confidence} | {r.rationale.replace('|', '/')} |")
    lines += [
        "",
        "## How the rules are kept honest (all automated in `tests/test_rules.py`)",
        "",
        "* every rule has positive examples that MUST match and negative examples that must NOT,",
        "* unknown, revoked and deprecated technique IDs are rejected at startup (the pipeline will not run),",
        "* the tactic must belong to the technique in the snapshot,",
        "* every regex is timed against hostile 4 KB inputs (ReDoS check),",
        "* commands that match nothing are stored with `mapped = false` and listed in the `v_unmapped_commands`",
        "  view, the Credentials & Commands dashboard and the weekly report, so new rules can be written.",
        "",
        "## Navigator layers",
        "",
        "* `docs/samples/attack-navigator-coverage-layer.json` - what HoneyLens **can detect** (this file's rules).",
        "* `docs/samples/attack-navigator-layer.json` - what was **seen** in the sample week (SIMULATED data).",
        "",
        "Open https://mitre-attack.github.io/attack-navigator/ → *Open Existing Layer* → *Upload from local*.",
        "",
        "## Adding a rule",
        "",
        "1. Pick the technique on attack.mitre.org; check it is not revoked/deprecated in v19.2.",
        "2. Add a YAML entry with id, regex, technique, tactic, confidence, rationale, positive and negative examples.",
        "3. `pytest tests/test_rules.py` then `python scripts/gen_mitre_coverage.py`.",
        "4. Re-score old sessions: `docker compose exec pipeline honeylens-pipeline --recompute`",
        "   (re-scores sessions; matches are stored at ingest time, so new rules apply to new events).",
        "",
        "## In short",
        "",
        "Commands are mapped to ATT&CK with YAML regex rules validated against a pinned official snapshot. When",
        "upgrading to v19 the validator rejected three revoked techniques, which is exactly why the check exists.",
        "Unmatched commands are tracked so coverage grows from real data.",
    ]
    (ROOT / "docs" / "MITRE_COVERAGE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (ROOT / "docs" / "samples").mkdir(parents=True, exist_ok=True)
    (ROOT / "docs" / "samples" / "attack-navigator-coverage-layer.json").write_text(
        json.dumps(navigator_layer(), indent=2) + "\n", encoding="utf-8")
    print(f"coverage {cov['coverage_percent']}% rules={cov['rules']} techniques={len(cov['techniques_covered'])}")


if __name__ == "__main__":
    main()
